Update orderedselect_input.pt #168
plone/plone.app.z3cform pull request #169
Opened 2023-06-01 07:27 UTC by szakitibi

Add "required" attribute to <select name="to"> for required fields. Refs "#168":://github.com/plone/plone.app.z3cform/issues/168

2023-06-01 07:27 UTC, mister-roboto commented
@szakitibi you need to sign the Plone Contributor Agreement to merge this pull request. 

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement

2023-06-01 07:27 UTC, mister-roboto commented
@szakitibi thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2023-06-01 07:39 UTC, mister-roboto commented
@szakitibi you need to sign the Plone Contributor Agreement to merge this pull request. 

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement

2023-06-01 07:48 UTC, szakitibi commented
Regarding "Plone Contributors Agreement verifier":
>  Plone Release Manager, the patch is so tiny as not to constitute a "creative work." 
I'm hereby transfer the intellectual property rights to the Plone Foundation for this PR.

2023-06-01 08:54 UTC, szakitibi commented
I'm not sure about the PR at all for two reasons:

**Reason 1:** Adding `required` to the `OrderedSelectWidget` is not sufficient fix, since it will still fail validation on backend. Thus it can be hacked by simply removing the `required` attribute. A cosmetic fix could do more harm this way allowing broken data into DB.

**Reason 2.** I've looked into the underlying logic in [`zope.scheam._field.List`](https://github.com/zopefoundation/zope.schema/blob/7.0.1/src/zope/schema/_field.py#L816). Seems like:

- [`Collection`](https://github.com/zopefoundation/zope.schema/blob/7.0.1/src/zope/schema/_field.py#L726) itself validates only that the provided value is from [`value_type` sequence](https://github.com/zopefoundation/zope.schema/blob/7.0.1/src/zope/schema/_field.py#L767-L779).
- [`Iterable`](https://github.com/zopefoundation/zope.schema/blob/7.0.1/src/zope/schema/_bootstrapfields.py#L446) only validates that value is indeed an iterable and not raises error on `iter(value)`. It also calls ['Container`](https://github.com/zopefoundation/zope.schema/blob/7.0.1/src/zope/schema/_bootstrapfields.py#L431) super classes validation checking value has `__contains__`. Then super [`Field`](https://github.com/zopefoundation/zope.schema/blob/7.0.1/src/zope/schema/_bootstrapfields.py#L342) checks type and `None` for required, which the empty list slips through.
-  [`MinMaxLen`](https://github.com/zopefoundation/zope.schema/blob/7.0.1/src/zope/schema/_bootstrapfields.py#L496) validates the length though

Seems like some widgets work by my logic (e.g. `plone.app.z3cform.widget.SelectFieldWidget`) and raise error for empty list. While others use a different logic (e.g. `z3c.form.browser.orderedselect.OrderedSelectWidget`) not raising error and accepting empty list.

No it could happen that I'm assuming something here and the `List` field (even if it is `required=True`) is normal to accept empty list. To get a validation error it should be always pared with `min_length=1`.

Note: If this is the case, then 'SelectWdiget' and 'AjaxSelectWdigets' raises error for no reason?

2023-06-04 07:39 UTC, gforcada commented
Hi! First of all thanks for the contribution! 🎉 

I'm unfortunately not an expert on the validation part, but even if some further work might be needed on the validation logic, marking a field as required is a good starting point IMHO.

Maybe some others have a better insight?

/cc @petschki @thet @jensens ? 😄

2023-06-04 15:06 UTC, jensens commented
From the logic POV, passing the views required is the right thing to to AFAICT.

2023-06-04 18:15 UTC, petschki requested changes

2023-06-04 18:15 UTC, petschki commented on plone/app/z3cform/templates/orderedselect_input.pt
> +                  required required | nothing;
I'd follow best practice of the other widget templates and use a onelineer

```suggestion
                  required python:view.required and 'required' or None;
```

and remove the `tal:define` line above.

2023-06-05 07:27 UTC, petschki commented
@szakitibi thanks for this one ... please see my successor with your changes. As I've mentioned you in the changenote, you might feel motivated to sign our contributors agreement. It's definitely worth it 😉

2023-06-05 07:27 UTC, closed without merging