Add support for accept attribute on file input.
plone/plone.app.z3cform pull request #200
Opened 2024-03-14 00:31 UTC by thet

If the widget's field - if there is one - has  set (the  field has  set by default) the allowed content types are rendered as  attribute on the file input.

This already restricts the allowed file types before uploading while still being checked on the server side too.

Fixes: https://github.com/plone/plone.formwidget.namedfile/issues/66 Depeds on:
- https://github.com/plone/plone.namedfile/pull/158
- https://github.com/plone/plone.formwidget.namedfile/pull/67

2024-03-14 00:31 UTC, mister-roboto commented
@thet thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-03-15 11:01 UTC, thet commented
@jenkins-plone-org please run jobs

2024-03-15 11:24 UTC, mauritsvanrees requested changes
I tried it out and it works in combination with the other PRs.

I have added suggestions to add `|nothing` so it does not break when this code is used in combination with a field/widget that does not have an `accept` attribute.  Maybe someone is using this on a field that we do not expect.

With those `|nothing` added, the input still works when I try it with an old release of `plone.formwidget.namedfile`.

2024-03-15 11:24 UTC, mauritsvanrees commented on plone/app/z3cform/templates/file_input.pt
> +         accept="${view/accept}"
```suggestion
         accept="${view/accept|nothing}"
```

2024-03-15 11:24 UTC, mauritsvanrees commented on plone/app/z3cform/templates/file_input.pt
> +       tal:condition="view/accept"
```suggestion
       tal:condition="view/accept|nothing"
```

2024-03-15 11:24 UTC, mauritsvanrees commented on plone/app/z3cform/templates/image_input.pt
> +         accept="${view/accept}"
```suggestion
         accept="${view/accept|nothing}"
```

2024-03-15 11:24 UTC, mauritsvanrees commented on plone/app/z3cform/templates/image_input.pt
> +       tal:condition="view/accept"
```suggestion
       tal:condition="view/accept|nothing"
```

2024-03-15 13:41 UTC, mauritsvanrees approved these changes

2024-03-15 13:47 UTC, mauritsvanrees commented
I have released a new `plone.formwidgets.namedfile` and depend on it.  It is up in the constraints on dist.plone.org.  Tests pass now.

But the dependencies check fails.  Should have nothing to do with this PR.  I am on it, trying an update with `plone/meta`.

2024-03-15 13:55 UTC, mauritsvanrees commented
All GitHub Actions pass.  Now try Jenkins again:

@jenkins-plone-org please run jobs

2024-03-15 15:37 UTC, merged